App\Domain\User\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username

  properties:
    username:
      - NotBlank: ~
      - Length:
          min: 3
          max: 255
          minMessage: 'Username must be at least {{ limit }} characters'
          maxMessage: 'Username cannot be more than {{ limit }} characters'

    password:
      - NotBlank: ~
      - Length:
          min: 6
          max: 100
          minMessage: 'Password must be at least {{ limit }} characters'
          maxMessage: 'Password cannot be more than {{ limit }} characters'
